stages:
  - build_staging  
  - deploy_staging
  - build_prod
  - deploy_prod


build_staging:
  stage:  build_staging
  tags:
    - cultbooking-ci
  only: 
    - staging
  script: 
    - mvn clean install
    - ssh gitlab-runner@$STAGING_SERVER "sudo rm -rf $STAGING_HOME/* && exit"
    - scp -r $STAGING_SRC  gitlab-runner@$STAGING_SERVER:$STAGING_HOME


deploy_staging:
  stage:  deploy_staging
  tags:
    - cultbooking-ci
  only: 
    - staging
  script: 
    - ssh gitlab-runner@$STAGING_SERVER "sudo systemctl stop reports.service && sleep 2 && sudo systemctl start reports.service && exit " 

build_prod:
  stage:  build_prod
  tags:
    - cultbooking-ci
  only: 
    - production
  script: 
    - mvn clean install
    - ssh gitlab-runner@$PROD_SERVER "sudo rm -rf $PROD_HOME/* && exit"
    - scp -r $PROD_SRC  gitlab-runner@$PROD_SERVER:$PROD_HOME


deploy_prod:
  stage:  deploy_prod
  tags:
    - cultbooking-ci
  only: 
    - production
  script: 
    - ssh gitlab-runner@$PROD_SERVER "sudo systemctl stop reports.service && sleep 2 && sudo systemctl start reports.service && exit "     