package com.property.report.model.enums;

public enum SocialMediaNetwork {

    DISCORD, DOUYIN, FACEBOOK, IMO, INSTAGRAM, KUAISHOU, LIKEE, LINE, LINKEDIN,
    MESSENGER, PICSTART, PINTEREST, QQ, QUORA, QZONE, REDDIT, SKYPE, SNAPCHAT,
    STACK_EXCHANGE, TEAMS, TELEGRAM, TIEBA, TIKTOK, TWITCH, TWITTER, VEVO,
    VIBER, WECHAT, WEIBO, WHATSAPP, YOUTUBE

}
